import os
from open_bus_siri_requester.config import OPEN_BUS_SIRI_STORAGE_ROOTPATH


DEBUG = os.environ.get('DEBUG') == 'yes'
OPEN_BUS_SIRI_ETL_ROOTPATH = os.path.join(OPEN_BUS_SIRI_STORAGE_ROOTPATH, 'etl')
SNAPSHOT_DOWNLOAD_REMOTE_URL = 'https://openbus-stride-public.s3.eu-west-1.amazonaws.com/stride-siri-requester'

OPEN_BUS_STRIDE_PUBLIC_S3_BUCKET_NAME = os.environ.get('OPEN_BUS_STRIDE_PUBLIC_S3_BUCKET_NAME') or 'openbus-stride-public'
OPEN_BUS_STRIDE_PUBLIC_S3_WRITE_ACCESS_KEY_ID = os.environ.get('OPEN_BUS_STRIDE_PUBLIC_S3_WRITE_ACCESS_KEY_ID')
OPEN_BUS_STRIDE_PUBLIC_S3_WRITE_SECRET_ACCESS_KEY = os.environ.get('OPEN_BUS_STRIDE_PUBLIC_S3_WRITE_SECRET_ACCESS_KEY')
OPEN_BUS_STRIDE_PUBLIC_S3_SIRI_REQUESTER_OBJECT_PREFIX = os.environ.get('OPEN_BUS_STRIDE_PUBLIC_S3_SIRI_REQUESTER_OBJECT_PREFIX') or 'stride-siri-requester'
