name: CI
on:
  push:
jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - env:
        DOCKER_APP_IMAGE_NAME: "docker.pkg.github.com/hasadna/open-bus-siri-etl/open-bus-siri-etl"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HASADNA_K8S_DEPLOY_KEY: ${{ secrets.HASADNA_K8S_DEPLOY_KEY }}
      run: |
        echo "${GITHUB_TOKEN}" | docker login docker.pkg.github.com -u hasadna --password-stdin &&\
        if docker pull "${DOCKER_APP_IMAGE_NAME}:latest"; then
          CACHE_FROM_ARG="--cache-from ${DOCKER_APP_IMAGE_NAME}:latest"
        else
          CACHE_FROM_ARG=""
        fi &&\
        docker build $CACHE_FROM_ARG -t app . &&\
        docker tag app "${DOCKER_APP_IMAGE_NAME}:${GITHUB_SHA}" &&\
        docker push "${DOCKER_APP_IMAGE_NAME}:${GITHUB_SHA}" &&\
        docker run --rm --name stride-db -e POSTGRES_PASSWORD=123456 -p 5432:5432 -d postgres:13 &&\
        sleep 2 &&\
        docker run \
          --network host \
          -e SQLALCHEMY_URL=postgresql://postgres:123456@localhost \
          --rm --name stride-db-migrations \
          docker.pkg.github.com/hasadna/open-bus-stride-db/open-bus-stride-db:1d3b939529667e18f5bc415679cc844c9d9c6afa &&\
        docker run \
          --network host \
          -e SQLALCHEMY_URL=postgresql://postgres:123456@localhost \
          -e DEBUG=yes \
          -v `pwd`:/srv --entrypoint bash app -c "pip install -r tests/requirements.txt && pytest" &&\
        if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
          docker tag app "${DOCKER_APP_IMAGE_NAME}:latest" &&\
          docker push "${DOCKER_APP_IMAGE_NAME}:latest" &&\
          if ! git log -1 --pretty=format:"%s" | grep -- --no-deploy; then
            cd `mktemp -d` &&\
            echo "${HASADNA_K8S_DEPLOY_KEY}" > hasadna_k8s_deploy_key &&\
            chmod 400 hasadna_k8s_deploy_key &&\
            export GIT_SSH_COMMAND="ssh -i `pwd`/hasadna_k8s_deploy_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" &&\
            git clone git@github.com:hasadna/hasadna-k8s.git &&\
            cd hasadna-k8s &&\
            python update_yaml.py '{"openbus":{"siriEtlImage":"'"${DOCKER_APP_IMAGE_NAME}:${GITHUB_SHA}"'"}}' ./values.auto-updated.yaml &&\
            git config --global user.name "Open Bus Siri ETL CI" &&\
            git config --global user.email "open-bus-siri-etl-ci@localhost" &&\
            git add ./values.auto-updated.yaml && git commit -m "automatic update of open bus siri etl" &&\
            git push origin master
          fi
        fi
